export const QUERY_KEYS = {
  ADMIN_DASHBOARD: ['admin-dashboard'],
  NUTRITIONIST_DASHBOARD: ['nutritionist-dashboard'],
  PROFILE: ['profile'],
  USERS: ['users'],
  USER: id => ['user', id],
  PENDING_CERTIFICATES_COUNT: ['pending-certificates-count'],
  INGREDIENTS: ['ingredients'],
  INGREDIENT: id => ['ingredient', id],
  COLLECTIONS: ['collections'],
  COLLECTION: id => ['collection', id],
  DISHES: ['dishes'],
  DISH: id => ['dish', id],
  SCHEDULES: ['schedules'],
  POSTS: ['posts'],
  POST: id => ['post', id],
  SCHEDULE: id => ['schedule', id],
  DISH_NUTRITION_DETAIL: id => ['dish_nutrition_detail', id],
  GROCERIES: ['groceries'],
  PAYMENTS: ['payments'],
  ACHIEVEMENTS: ['achievements'],
  NUTRITIONISTS: ['nutritionists'],
  NUTRITIONIST: id => ['nutritionist', id],
  EXERCISES: ['exercises'],
  EXERCISE: id => ['exercise', id],
  FEEDBACKS: ['feedbacks'],
  PRIVATE_DISHES: ['private-dishes'],
  PRIVATE_DISH: id => ['private-dish', id]
};
